apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dominion-api
  namespace: dominion
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "32m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.dominion.local
      secretName: dominion-tls
  rules:
    - host: api.dominion.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dominion-api
                port:
                  number: 8000
