"""
OMEGA — Trend Following Engine (Core)
Phase 17 — Engineering Spec v3.0

H1/H4 swing strategy: trend identification, entry refinement,
exit management. OMEGA complements ALPHA's M1 scalping.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

import numpy as np

from aphelion.flow.omega import OmegaSignalGenerator as BaseOmegaEngine

logger = logging.getLogger(__name__)


@dataclass
class OmegaConfig:
    """OMEGA strategy configuration."""
    # Trend identification
    trend_ema_fast: int = 50
    trend_ema_slow: int = 200
    min_adx: float = 25.0
    # Entry
    entry_pullback_pct: float = 0.003
    min_rr_ratio: float = 2.0
    # Exit
    atr_sl_multiplier: float = 3.0
    atr_tp_multiplier: float = 5.0
    trail_atr_multiplier: float = 2.5
    # Position
    max_concurrent_positions: int = 2


@dataclass
class OmegaSignal:
    """Signal generated by OMEGA."""
    direction: int        # -1, 0, 1
    confidence: float
    trend_strength: float
    entry_price: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    reason: str = ""


class OmegaCoreEngine:
    """
    OMEGA core strategy engine.
    Identifies trends on H1/H4 and refines entries/exits.
    """

    def __init__(self, config: Optional[OmegaConfig] = None):
        self._config = config or OmegaConfig()
        self._trend_state: str = "FLAT"
        self._positions: List[dict] = []

    def identify_trend(
        self,
        closes: np.ndarray,
        adx: float,
    ) -> Tuple[str, float]:
        """Identify the current trend state."""
        cfg = self._config
        if len(closes) < cfg.trend_ema_slow:
            return "FLAT", 0.0

        ema_fast = self._ema(closes, cfg.trend_ema_fast)
        ema_slow = self._ema(closes, cfg.trend_ema_slow)

        if ema_fast > ema_slow and adx >= cfg.min_adx:
            strength = min(1.0, (ema_fast - ema_slow) / ema_slow * 100)
            self._trend_state = "BULL"
            return "BULL", strength
        elif ema_fast < ema_slow and adx >= cfg.min_adx:
            strength = min(1.0, (ema_slow - ema_fast) / ema_slow * 100)
            self._trend_state = "BEAR"
            return "BEAR", strength

        self._trend_state = "FLAT"
        return "FLAT", 0.0

    def generate_signal(
        self,
        closes: np.ndarray,
        highs: np.ndarray,
        lows: np.ndarray,
        adx: float,
        atr: float,
    ) -> OmegaSignal:
        """Generate a swing trade signal."""
        trend, strength = self.identify_trend(closes, adx)

        if trend == "FLAT" or strength < 0.1:
            return OmegaSignal(direction=0, confidence=0.0, trend_strength=strength, reason="NO_TREND")

        current = float(closes[-1])
        cfg = self._config

        # Check for pullback entry
        if trend == "BULL":
            ema_fast = self._ema(closes, cfg.trend_ema_fast)
            pullback = (ema_fast - current) / ema_fast
            if pullback > cfg.entry_pullback_pct:
                sl = current - atr * cfg.atr_sl_multiplier
                tp = current + atr * cfg.atr_tp_multiplier
                rr = (tp - current) / (current - sl) if current > sl else 0
                if rr >= cfg.min_rr_ratio:
                    return OmegaSignal(
                        direction=1, confidence=min(0.9, strength * 0.8),
                        trend_strength=strength, entry_price=current,
                        stop_loss=sl, take_profit=tp,
                        reason="BULL_PULLBACK_ENTRY",
                    )

        elif trend == "BEAR":
            ema_fast = self._ema(closes, cfg.trend_ema_fast)
            pullback = (current - ema_fast) / ema_fast
            if pullback > cfg.entry_pullback_pct:
                sl = current + atr * cfg.atr_sl_multiplier
                tp = current - atr * cfg.atr_tp_multiplier
                rr = (current - tp) / (sl - current) if sl > current else 0
                if rr >= cfg.min_rr_ratio:
                    return OmegaSignal(
                        direction=-1, confidence=min(0.9, strength * 0.8),
                        trend_strength=strength, entry_price=current,
                        stop_loss=sl, take_profit=tp,
                        reason="BEAR_PULLBACK_ENTRY",
                    )

        return OmegaSignal(direction=0, confidence=0.0, trend_strength=strength, reason="NO_SETUP")

    @staticmethod
    def _ema(data: np.ndarray, period: int) -> float:
        mult = 2.0 / (period + 1)
        ema = float(data[0])
        for p in data[1:]:
            ema = (float(p) - ema) * mult + ema
        return ema
